#DB configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/jaijober?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mariadb://69.62.76.153:3306/apitrans_db
spring.datasource.username=apitrans_db
spring.datasource.password=W2BPUR4pwHCPdxchH9tQ
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Email configuration (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Secret (minimum 32 chars)
app.jwtSecret=ROgUGZKeve+H/eq94bntSSy8K8arvRM8j9IwGup6X5QkcjihcGn2pBzKXzFwvgkiLukJv57t7aPfeRRmaOmBuQ==
app.jwtExpirationMs=86400000