version: '3.8'

services:
  app:
    build: .
    container_name: java_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://69.62.76.153:3306/apitrans_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=apitrans_db
      - SPRING_DATASOURCE_PASSWORD=W2BPUR4pwHCPdxchH9tQ