spring.application.name=transport-new

spring.datasource.url=jdbc:mariadb://69.62.76.153:3306/apitrans_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=apitrans_db
spring.datasource.password=W2BPUR4pwHCPdxchH9tQ
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Email configuration (Gmail example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info@webgodam.com
spring.mail.password=kbeg qgen tjjy pplb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.starttls.protocols=TLSv1.2
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT Secret (minimum 32 chars)
app.jwtSecret=ROgUGZKeve+H/eq94bntSSy8K8arvRM8j9IwGup6X5QkcjihcGn2pBzKXzFwvgkiLukJv57t7aPfeRRmaOmBuQ==
app.jwtExpirationMs=86400000


# Enable the console
spring.h2.console.enabled=true

# Change the path to whatever you want (e.g., localhost:8080/db-admin)
spring.h2.console.path=/db-admin

# Allow non-local access if you are deploying it on a server
spring.h2.console.settings.web-allow-others=true
